/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Users;

/**
 *
 * @author TT
 */
public class BlockDeleteDialog extends javax.swing.JDialog {

    /**
     * Creates new form BlockDeleteDialog
     */
    DBConnection dbc = new DBConnection();
    Users u;
    int id;
    String keyword;

    public BlockDeleteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public BlockDeleteDialog(java.awt.Frame parent, boolean modal, int id, String keyword) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        this.id = id;
        this.keyword = keyword;

        if (keyword == "Block") {
            u = dbc.findByid(id);
            lblKeyWord.setText(u.getName() + " " + u.getSurname() + " " + "bloklansınmı ?");
        }
        if (keyword == "UnBlock") {
            u = dbc.findByid(id);
            lblKeyWord.setText(u.getName() + " " + u.getSurname() + " " + "blokdan cıxarılsınmı ?");
        }
        if (keyword == "DeleteEquip") {
            lblKeyWord.setText("Seçdiyiniz vasitə bloklansınmı ?");
        }
        if (keyword == "UnDeleteEquip") {
            lblKeyWord.setText("Seçdiyiniz vasitə blokdan çıxarılsınmı ?");
        }
        if (keyword == "DeleteTheRoute") {
            lblKeyWord.setText("Seçdiyiniz sifariş silinsinmi ?");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKeyWord = new javax.swing.JLabel();
        btnNo = new javax.swing.JButton();
        btnYes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        lblKeyWord.setBackground(new java.awt.Color(255, 255, 255));
        lblKeyWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblKeyWord.setForeground(new java.awt.Color(153, 0, 0));
        lblKeyWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeyWord.setText("KeyWord");

        btnNo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNo.setText("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        btnYes.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnYes.setText("Yes");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKeyWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnYes)
                        .addGap(18, 18, 18)
                        .addComponent(btnNo)
                        .addGap(0, 80, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNo, btnYes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNo, btnYes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        dispose();
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        if (keyword == "Block") {
            dbc.blockUsers(id);
            dispose();
        }
        if (keyword == "UnBlock") {
            dbc.unblockUsers(id);
            dispose();
        }
        if (keyword == "DeleteEquip") {
            dbc.blockEquipment(id);
            dispose();
        }
        if (keyword == "UnDeleteEquip") {
            dbc.unBlockEquipment(id);
            dispose();
        }
        if (keyword == "DeleteTheRoute") {
            dbc.deleteTheRoute(id);
            dispose();
        }

    }//GEN-LAST:event_btnYesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlockDeleteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlockDeleteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlockDeleteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlockDeleteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BlockDeleteDialog dialog = new BlockDeleteDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel lblKeyWord;
    // End of variables declaration//GEN-END:variables
}
