/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Notifications;
import Pojo.TheRoute;
import Pojo.Users;
import java.awt.Color;

/**
 *
 * @author TT
 */
public class CancelOrderDialog extends javax.swing.JDialog {

    /**
     * Creates new form CancelOrderDialog
     */
    DBConnection dbc = new DBConnection();
    Users u = null;
    int Nid;
    String keyword = null;
    Notifications n = null;
    TheRoute r = null;

    public CancelOrderDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public CancelOrderDialog(java.awt.Frame parent, boolean modal, Users u, int Nid, String keyword) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;
        this.Nid = Nid;
        this.keyword = keyword;
        n = dbc.findByNid(Nid);
        r = dbc.findByTheRouteId(n.getRoute_id());

        if (keyword == "CancelOrderClient") {
            lblMessage.setText("Sifarişiniz ləğv edilsinmi ?");
        }
        if (keyword == "CancelOrderOwner") {
            lblMessage.setText("Sifariş ləğv edilsinmi ?");
        }
        if (keyword == "AcceptOrder") {
            lblMessage.setText("Sifariş təsdiq edilsinmi ?");
            btnOk.setText("Təstiq et");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblX = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        lblCancelOrderBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 1, 29, 25));

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Sifarişiniz ləğv edilsinmi ?");
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 190, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Geri");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, 23));

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOk.setText("Ləğv et");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 23));

        lblCancelOrderBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCancelOrderBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ChangePasswordBCK.png"))); // NOI18N
        lblCancelOrderBCK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblCancelOrderBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        if (keyword == "CancelOrderClient") {
            MyOrder my = new MyOrder(u);
            my.setVisible(true);
            dispose();
        }
        if (keyword == "CancelOrderOwner") {
            MyNotifications my = new MyNotifications(u);
            my.setVisible(true);
            dispose();
        }
        if (keyword == "AcceptOrder") {
            MyNotifications my = new MyNotifications(u);
            my.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (keyword == "CancelOrderClient") {
            if (n.getStatus() == 1) {
                dbc.cancelOrderClient(Nid);
                MyOrder my = new MyOrder(u);
                my.setVisible(true);
                dispose();
            } else if (n.getStatus() == 0) {
                int count_Pass = r.getPassenger() + n.getCount_passenger();
                double count_Lugg = r.getLuggage() + n.getCount_luggage();
                dbc.cancelOrderClient0(Nid, n.getRoute_id(), count_Pass, count_Lugg);
                MyNotifications my = new MyNotifications(u);
                my.setVisible(true);
                dispose();
            } else {
                lblMessage.setText("Bu sifariş artıq ləğv olunub!");
                lblMessage.setForeground(Color.red);
            }
        }
        if (keyword == "CancelOrderOwner") {
            if (n.getStatus() == 1) {
                dbc.cancelOrderOwner1(Nid);
                MyNotifications my = new MyNotifications(u);
                my.setVisible(true);
                dispose();
            } else if (n.getStatus() == 0) {
                int count_Pass = r.getPassenger() + n.getCount_passenger();
                double count_Lugg = r.getLuggage() + n.getCount_luggage();
                dbc.cancelOrderOwner0(Nid, n.getRoute_id(), count_Pass, count_Lugg);
                MyNotifications my = new MyNotifications(u);
                my.setVisible(true);
                dispose();
            } else {
                lblMessage.setText("Bu sifariş artıq ləğv olunub!");
                lblMessage.setForeground(Color.red);
            }
        }
        if (keyword == "AcceptOrder") {
            if (n.getStatus() == 1) {
                int count_Pass = r.getPassenger() - n.getCount_passenger();
                double count_Lugg = r.getLuggage() - n.getCount_luggage();
                dbc.acceptOrder(Nid, n.getRoute_id(), count_Pass, count_Lugg);
                MyNotifications my = new MyNotifications(u);
                my.setVisible(true);
                dispose();
            } else if (n.getStatus() == 0) {
                lblMessage.setText("Sifarişiniz artıq təstiq olunmuşdur!");
                lblMessage.setForeground(Color.red);
            } else if (n.getStatus() == 3) {
                lblMessage.setText("Ləğv edilmiş sifariş təsdiq edilə bilməz!");
                lblMessage.setForeground(Color.red);
            }
        }


    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (keyword == "CancelOrderClient") {
            MyOrder my = new MyOrder(u);
            my.setVisible(true);
            dispose();
        }
        if (keyword == "CancelOrderOwner") {
            MyNotifications my = new MyNotifications(u);
            my.setVisible(true);
            dispose();
        }
        if (keyword == "AcceptOrder") {
            MyNotifications my = new MyNotifications(u);
            my.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CancelOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CancelOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CancelOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CancelOrderDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CancelOrderDialog dialog = new CancelOrderDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel lblCancelOrderBCK;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
