/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Users;
import java.awt.Color;

/**
 *
 * @author TT
 */
public class FreezeAccountDialog extends javax.swing.JDialog {

    /**
     * Creates new form FreezeAccountDialog
     */
    DBConnection dbc = new DBConnection();
    Users u = null;
    String keyword = null;

    public FreezeAccountDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public FreezeAccountDialog(java.awt.Frame parent, boolean modal, Users u, String keyword) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;
        this.keyword = keyword;

        if (keyword == "Freeze") {
            lblMessage.setText("Hesabınız dondurulsunmu ?");
            btnFreeze.setText("Dondur");
        }
        if (keyword == "DeleteImage") {
            lblMessage.setText("Şəkil silinsinmi ?");
            btnFreeze.setText("Sil");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        btnFreeze = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblX = new javax.swing.JLabel();
        lblFreezeBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText("Hesabınız dondurulsunmu ?");
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, -1));

        btnFreeze.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFreeze.setText("Dondur");
        btnFreeze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreezeActionPerformed(evt);
            }
        });
        getContentPane().add(btnFreeze, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Ləğv et");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 1, 29, 25));

        lblFreezeBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFreezeBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ChangePasswordBCK.png"))); // NOI18N
        lblFreezeBCK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblFreezeBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        UpdatePage up = new UpdatePage(u);
        up.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnFreezeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFreezeActionPerformed
        if (keyword == "Freeze") {
            dbc.freezeAccount(u);
            Login l = new Login();
            l.setVisible(true);
            u = null;
            dispose();
        }
        if (keyword == "DeleteImage") {
            u.setImage(null);
            UpdatePage up = new UpdatePage(u);
            up.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnFreezeActionPerformed

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        UpdatePage up = new UpdatePage(u);
        up.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FreezeAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FreezeAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FreezeAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FreezeAccountDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FreezeAccountDialog dialog = new FreezeAccountDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFreeze;
    private javax.swing.JLabel lblFreezeBCK;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
