/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Users;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author TT
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    DBConnection dbc = new DBConnection();
    Users u = null;

    public Login() {
        initComponents();
        setLocationRelativeTo(this);
        lblError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblRegistration = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblLoginBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 160, -1));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setOpaque(true);
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, 20));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, -1));

        lblRegistration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrationMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 12, 174, 42));

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        getContentPane().add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 375, 110, 25));

        lblLoginBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LoginBCK.png"))); // NOI18N
        getContentPane().add(lblLoginBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            u = dbc.loginUsers(txtUsername.getText(), txtPassword.getText());
            if (u != null) {
                if (u.getRole() == 0) {
                    AdminPage admin = new AdminPage(u);
                    admin.setVisible(true);
                    dispose();
                } else {
                    if (u.getStatus() != 2) {
                        dbc.deleteTheRouteForDates();
                        MyProfile mp = new MyProfile(u);
                        mp.setVisible(true);
                        dispose();
                    } else {
                        lblError.setVisible(true);
                        lblError.setForeground(Color.red);
                        lblError.setBackground(Color.white);
                        lblError.setText("Siz bloklanmisiniz!");
                    }
                }

            } else {
                lblError.setVisible(true);
                lblError.setForeground(Color.red);
                lblError.setBackground(Color.white);
                lblError.setText("Sifre ve ya istifadeci adi yanlisdir!");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblRegistrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrationMouseClicked
        RegisterUser register = new RegisterUser();
        register.setVisible(true);
        dispose();

    }//GEN-LAST:event_lblRegistrationMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                u = dbc.loginUsers(txtUsername.getText(), txtPassword.getText());
                if (u != null) {
                    if (u.getRole() == 0) {
                        AdminPage admin = new AdminPage(u);
                        admin.setVisible(true);
                        dispose();
                    } else {
                        if (u.getStatus() != 2) {
                            dbc.deleteTheRouteForDates();
                            MyProfile mp = new MyProfile(u);
                            mp.setVisible(true);
                            dispose();
                        } else {
                            lblError.setVisible(true);
                            lblError.setForeground(Color.red);
                            lblError.setBackground(Color.white);
                            lblError.setText("Siz bloklanmisiniz!");
                        }
                    }

                } else {
                    lblError.setVisible(true);
                    lblError.setForeground(Color.red);
                    lblError.setBackground(Color.white);
                    lblError.setText("Sifre ve ya istifadeci adi yanlisdir!");
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLoginBCK;
    private javax.swing.JLabel lblRegistration;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
