/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Messages;
import Pojo.Users;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author TT
 */
public class MessagesPage extends javax.swing.JFrame {

    /**
     * Creates new form MessagesPage
     */
    DBConnection dbc = new DBConnection();
    Users u = null;
    Users u_from = null;

    DefaultListModel<Users> listUsersModel = new DefaultListModel<Users>();
    DefaultListModel<String> listMessagesModel = new DefaultListModel<String>();

    public MessagesPage() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public MessagesPage(Users u) {
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;
        for (Users us : dbc.listUsersForMessages(u.getId())) {
            listUsersModel.addElement(us);
        }

        listUsers.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                listMessagesModel.removeAllElements();
                if (!e.getValueIsAdjusting()) {
                    Users use = (Users) listUsers.getSelectedValue();
                    dbc.readUnread(use.getId());
                    u_from = use;
                    for (Messages m : dbc.listMessages(use.getId(), u.getId())) {
                        listMessagesModel.addElement(dbc.findByid(m.getUser_id_from()).getName() + ": " + m.getMessage());
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblX = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listMessages = new javax.swing.JList();
        txtWriteMessages = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblMessagesBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 1, 29, 25));

        listUsers = new javax.swing.JList(listUsersModel);
        listUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listUsers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane1.setViewportView(listUsers);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 470));

        listMessages = new javax.swing.JList(listMessagesModel);
        listMessages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listMessages.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jScrollPane2.setViewportView(listMessages);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 480, 430));

        txtWriteMessages.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtWriteMessages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtWriteMessages.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtWriteMessagesKeyPressed(evt);
            }
        });
        getContentPane().add(txtWriteMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 350, 20));

        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BtnSendMessageIcon.png"))); // NOI18N
        btnSend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 40, 20));

        lblMessagesBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessagesBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MessagesBCK.png"))); // NOI18N
        lblMessagesBCK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMessagesBCK.setOpaque(true);
        getContentPane().add(lblMessagesBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.WHITE);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        MyProfile mp = new MyProfile(u);
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if (!txtWriteMessages.getText().isEmpty()) {
            listMessagesModel.addElement(u.getName() + ": " + txtWriteMessages.getText());
            dbc.insertMessage(u.getId(), u_from.getId(), txtWriteMessages.getText());
            txtWriteMessages.setText("");
        } else {
            ErrorDialog er = new ErrorDialog(this, true, "Boşluq xetası");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void txtWriteMessagesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWriteMessagesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtWriteMessages.getText().isEmpty()) {
                listMessagesModel.addElement(u.getName() + ": " + txtWriteMessages.getText());
                dbc.insertMessage(u.getId(), u_from.getId(), txtWriteMessages.getText());
                txtWriteMessages.setText("");
            } else {
                ErrorDialog er = new ErrorDialog(this, true, "Boşluq xetası");
                er.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtWriteMessagesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessagesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMessagesBCK;
    private javax.swing.JLabel lblX;
    private javax.swing.JList listMessages;
    private javax.swing.JList listUsers;
    private javax.swing.JTextField txtWriteMessages;
    // End of variables declaration//GEN-END:variables
}
