/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Models.EquipmentTableModel;
import Pojo.Users;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author TT
 */
public class MyEquipment extends javax.swing.JFrame {

    /**
     * Creates new form MyEquipment
     */
    DBConnection dbc = new DBConnection();
    Users u = null;

    public MyEquipment() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public MyEquipment(Users u) {
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;

        refresh();

    }

    public void refresh() {
        List<String> h = new ArrayList<String>();
        h.add("Nomre");
        h.add("Marka");
        h.add("Model");
        h.add("Ban növü");
        h.add("Kondisioner");
        h.add("Status");

        EquipmentTableModel model = new EquipmentTableModel(dbc.listEquipmentForEquipTable(u.getId()), h);
        tblMyEquipment.setModel(model);
        tblMyEquipment.getColumnModel().getColumn(0).setMinWidth(0);
        tblMyEquipment.getColumnModel().getColumn(0).setMaxWidth(0);
        tblMyEquipment.getColumnModel().getColumn(0).setWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMyEquipment = new javax.swing.JTable();
        lblAdd = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblX = new javax.swing.JLabel();
        btnUnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblMyEquipBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(tblMyEquipment);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 712, 200));

        lblAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdd.setText("+ Vasitə əlavə et");
        lblAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddMouseClicked(evt);
            }
        });
        getContentPane().add(lblAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDelete.setText("Vasitəni Deavtiv et");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, -1, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 25));

        btnUnDelete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUnDelete.setText("Vasitəni Akvtiv et");
        btnUnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, -1, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Geri");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lblMyEquipBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMyEquipBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyEquipment.png"))); // NOI18N
        getContentPane().add(lblMyEquipBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddMouseClicked
        MyEquipmentInsert me = new MyEquipmentInsert(u);
        me.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblAddMouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        MyProfile mp = new MyProfile(u);
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            BlockDeleteDialog b = new BlockDeleteDialog(this, true, Integer.parseInt(tblMyEquipment.getValueAt(tblMyEquipment.getSelectedRow(), 0).toString()), "DeleteEquip");
            b.setVisible(true);
            refresh();
        } catch (Exception e) {
            ErrorDialog er = new ErrorDialog(this, true, "Her hansı bir obyekt seçilməyib");
            er.setVisible(true);

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnDeleteActionPerformed
        try {
            BlockDeleteDialog b = new BlockDeleteDialog(this, true, Integer.parseInt(tblMyEquipment.getValueAt(tblMyEquipment.getSelectedRow(), 0).toString()), "UnDeleteEquip");
            b.setVisible(true);
            refresh();
        } catch (Exception e) {
            ErrorDialog er = new ErrorDialog(this, true, "Her hansı bir obyekt seçilməyib");
            er.setVisible(true);

        }
    }//GEN-LAST:event_btnUnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MyProfile mp = new MyProfile(u);
        mp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyEquipment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyEquipment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblMyEquipBCK;
    private javax.swing.JLabel lblX;
    private javax.swing.JTable tblMyEquipment;
    // End of variables declaration//GEN-END:variables
}
