/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Enums.BanTypes;
import Pojo.Equipment;
import Pojo.Users;
import java.awt.Color;

/**
 *
 * @author TT
 */
public class MyEquipmentInsert extends javax.swing.JFrame {

    /**
     * Creates new form MyEquipmentInsert
     */
    DBConnection dbc = new DBConnection();
    Users u = null;

    public MyEquipmentInsert() {
        initComponents();
        setLocationRelativeTo(this);
        rbNo.setSelected(true);
        lblError.setVisible(false);

        cbBanTipe.addItem("Seçim edin");
        for (BanTypes b : BanTypes.values()) {
            cbBanTipe.addItem(b);
        }
    }

    public MyEquipmentInsert(Users u) {
        initComponents();
        setLocationRelativeTo(this);
        this.u = u;
        rbNo.setSelected(true);
        lblError.setVisible(false);

        cbBanTipe.addItem("Seçim edin");
        for (BanTypes b : BanTypes.values()) {
            cbBanTipe.addItem(b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbGroupConditioner = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        cbBanTipe = new javax.swing.JComboBox();
        rbYes = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        btnCancel = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblEquipmentBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Marka");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Model");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Ban növü");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Kodisioner");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, -1, -1));

        txtBrand.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 25, 171, -1));

        txtModel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(txtModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 63, 171, -1));

        cbBanTipe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(cbBanTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 101, 171, -1));

        rbGroupConditioner.add(rbYes);
        rbYes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbYes.setText("Vardır");
        rbYes.setOpaque(false);
        getContentPane().add(rbYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 139, -1, -1));

        rbGroupConditioner.add(rbNo);
        rbNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbNo.setText("Yoxdur");
        rbNo.setOpaque(false);
        getContentPane().add(rbNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 139, -1, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Geri");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 69, -1));

        btnInsert.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnInsert.setText("Daxil et");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("Error label");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 180, 171, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 25));

        lblEquipmentBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEquipmentBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyEquipmentInsertBCK.png"))); // NOI18N
        getContentPane().add(lblEquipmentBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        MyEquipment me = new MyEquipment(u);
        me.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        if (cbBanTipe.getSelectedIndex() != 0) {
            Equipment e = new Equipment();
            e.setUser_id(u.getId());
            e.setBrand(txtBrand.getText());
            e.setModel(txtModel.getText());
            e.setBan_type(cbBanTipe.getSelectedItem().toString());
            if (rbNo.isSelected()) {
                e.setConditioner('N');
            } else {
                e.setConditioner('Y');
            }

            e.setStatus(1);
            dbc.insertEquipment(e);

            MyEquipment me = new MyEquipment(u);
            me.setVisible(true);
            dispose();
        } else {
            lblError.setVisible(true);
            lblError.setForeground(Color.red);
            lblError.setText("Ban tipi seçilməyib!");
        }


    }//GEN-LAST:event_btnInsertActionPerformed

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        MyEquipment me = new MyEquipment(u);
        me.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyEquipmentInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyEquipmentInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyEquipmentInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyEquipmentInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyEquipmentInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnInsert;
    private javax.swing.JComboBox cbBanTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblEquipmentBCK;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblX;
    private javax.swing.ButtonGroup rbGroupConditioner;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbYes;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtModel;
    // End of variables declaration//GEN-END:variables
}
