/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Notifications;
import Pojo.Users;
import com.sun.media.sound.SoftLimiter;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.management.Notification;
import javax.swing.ImageIcon;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author TT
 */
public class MyProfile extends javax.swing.JFrame {

    /**
     * Creates new form MyProfile
     */
    DBConnection dbc = new DBConnection();
    Users u = null;

    public MyProfile() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public MyProfile(Users u) {
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;

        lblNameSurname.setText(u.getName() + " " + u.getSurname());

        if (u.getImage() != null) {
            Image img = Toolkit.getDefaultToolkit().createImage(u.getImage()).getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon imageIcon = new ImageIcon(img);
            lblImage.setIcon(imageIcon);
        } else {
            lblImage.setIcon(lblImage.getIcon());
        }

        List<Notifications> list = dbc.listMyNotificationsForNewEvent(u.getId());
        lblNotificationCount.setText("" + list.size());

        List<Notifications> listn = dbc.listMyNotificationsForNewEventClient(u.getId());
        lblMyOrderCount.setText("" + listn.size());

        List<Integer> listm = dbc.countNewMessage(u.getId());
        lblMessagesCount.setText("" + listm.size());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImage = new javax.swing.JLabel();
        lblNameSurname = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblX = new javax.swing.JLabel();
        lblIWantGo = new javax.swing.JLabel();
        lblCarryManOrBox = new javax.swing.JLabel();
        lblSendBox = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        lblEquipment = new javax.swing.JLabel();
        lblMyRoute = new javax.swing.JLabel();
        lblNotificationCount = new javax.swing.JLabel();
        lblNotifications = new javax.swing.JLabel();
        lblMyOrderCount = new javax.swing.JLabel();
        lblMyOrder = new javax.swing.JLabel();
        lblMessagesCount = new javax.swing.JLabel();
        lblMessages = new javax.swing.JLabel();
        lblLine = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserProfile.png"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImage.setOpaque(true);
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 36, 100, 100));

        lblNameSurname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNameSurname.setText("Name Surname");
        lblNameSurname.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblNameSurnameMouseMoved(evt);
            }
        });
        lblNameSurname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNameSurnameMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNameSurnameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNameSurnameMouseExited(evt);
            }
        });
        getContentPane().add(lblNameSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 36, 164, 23));

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setText("Düzəliş et");
        btnUpdate.setHideActionText(true);
        btnUpdate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnUpdateMouseMoved(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 1, 29, 25));

        lblIWantGo.setBackground(new java.awt.Color(255, 255, 255));
        lblIWantGo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblIWantGo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblIWantGoMouseMoved(evt);
            }
        });
        lblIWantGo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIWantGoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIWantGoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblIWantGoMouseExited(evt);
            }
        });
        getContentPane().add(lblIWantGo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 110, 80));

        lblCarryManOrBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblCarryManOrBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblCarryManOrBoxMouseMoved(evt);
            }
        });
        lblCarryManOrBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCarryManOrBoxMouseClicked(evt);
            }
        });
        getContentPane().add(lblCarryManOrBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 110, 80));

        lblSendBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblSendBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSendBoxMouseMoved(evt);
            }
        });
        lblSendBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSendBoxMouseClicked(evt);
            }
        });
        getContentPane().add(lblSendBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 110, 80));

        lblLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogOut.setText("Çıxış");
        lblLogOut.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLogOutMouseMoved(evt);
            }
        });
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        getContentPane().add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 121, -1, -1));

        lblEquipment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEquipment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEquipment.setText("Vasitə");
        lblEquipment.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblEquipmentMouseMoved(evt);
            }
        });
        lblEquipment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEquipmentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEquipmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEquipmentMouseExited(evt);
            }
        });
        getContentPane().add(lblEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 94, -1, -1));

        lblMyRoute.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMyRoute.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblMyRoute.setText("Sifarişlərim");
        lblMyRoute.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMyRouteMouseMoved(evt);
            }
        });
        lblMyRoute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMyRouteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMyRouteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMyRouteMouseExited(evt);
            }
        });
        getContentPane().add(lblMyRoute, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 64, -1, -1));

        lblNotificationCount.setBackground(new java.awt.Color(204, 0, 0));
        lblNotificationCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNotificationCount.setForeground(new java.awt.Color(255, 255, 255));
        lblNotificationCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotificationCount.setText("0");
        lblNotificationCount.setOpaque(true);
        getContentPane().add(lblNotificationCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 15, 15));

        lblNotifications.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNotifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Notification Icon.png"))); // NOI18N
        lblNotifications.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblNotifications.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblNotificationsMouseMoved(evt);
            }
        });
        lblNotifications.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotificationsMouseClicked(evt);
            }
        });
        getContentPane().add(lblNotifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 30, 30));

        lblMyOrderCount.setBackground(new java.awt.Color(204, 0, 0));
        lblMyOrderCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMyOrderCount.setForeground(new java.awt.Color(255, 255, 255));
        lblMyOrderCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMyOrderCount.setText("0");
        lblMyOrderCount.setOpaque(true);
        getContentPane().add(lblMyOrderCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 15, 15));

        lblMyOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMyOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyOrder Icon.png"))); // NOI18N
        lblMyOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMyOrder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMyOrderMouseMoved(evt);
            }
        });
        lblMyOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMyOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMyOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMyOrderMouseExited(evt);
            }
        });
        getContentPane().add(lblMyOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 30, 30));

        lblMessagesCount.setBackground(new java.awt.Color(204, 0, 0));
        lblMessagesCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMessagesCount.setForeground(new java.awt.Color(255, 255, 255));
        lblMessagesCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessagesCount.setText("0");
        lblMessagesCount.setOpaque(true);
        getContentPane().add(lblMessagesCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 15, 15));

        lblMessages.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMessages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MessagesIcon.png"))); // NOI18N
        lblMessages.setText("jLabel1");
        lblMessages.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblMessages.setOpaque(true);
        lblMessages.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblMessagesMouseMoved(evt);
            }
        });
        lblMessages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMessagesMouseClicked(evt);
            }
        });
        getContentPane().add(lblMessages, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 30, 30));

        lblLine.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLine.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 36, 160, 50));

        lblBackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MyProfilePictureBCK.png"))); // NOI18N
        lblBackGround.setText("jLabel1");
        lblBackGround.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBackGround.setOpaque(true);
        getContentPane().add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        u = null;
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        UpdatePage update = new UpdatePage(u);
        update.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void lblIWantGoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIWantGoMouseEntered

    }//GEN-LAST:event_lblIWantGoMouseEntered

    private void lblIWantGoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIWantGoMouseExited
    }//GEN-LAST:event_lblIWantGoMouseExited

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        u = null;
        dispose();
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblCarryManOrBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarryManOrBoxMouseClicked
        IWantPassenger wp = new IWantPassenger(u);
        wp.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCarryManOrBoxMouseClicked

    private void lblEquipmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEquipmentMouseClicked
        MyEquipment me = new MyEquipment(u);
        me.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblEquipmentMouseClicked

    private void lblIWantGoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIWantGoMouseClicked
        IWantToGo iw = new IWantToGo(u);
        iw.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblIWantGoMouseClicked

    private void lblSendBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSendBoxMouseClicked
        IWantToSend iw = new IWantToSend(u);
        iw.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblSendBoxMouseClicked

    private void lblMyRouteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyRouteMouseClicked
        MyActiveRoutes myr = new MyActiveRoutes(u);
        myr.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMyRouteMouseClicked

    private void lblNotificationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotificationsMouseClicked
        MyNotifications my = new MyNotifications(u);
        my.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblNotificationsMouseClicked

    private void lblMyOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyOrderMouseClicked
        MyOrder m = new MyOrder(u);
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMyOrderMouseClicked

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        lblLogOut.setForeground(Color.white);
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
        lblLogOut.setForeground(Color.black);
    }//GEN-LAST:event_lblLogOutMouseExited

    private void lblEquipmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEquipmentMouseEntered
        lblEquipment.setForeground(Color.white);
    }//GEN-LAST:event_lblEquipmentMouseEntered

    private void lblEquipmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEquipmentMouseExited
        lblEquipment.setForeground(Color.black);
    }//GEN-LAST:event_lblEquipmentMouseExited

    private void lblMyRouteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyRouteMouseEntered
        lblMyRoute.setForeground(Color.white);
    }//GEN-LAST:event_lblMyRouteMouseEntered

    private void lblMyRouteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyRouteMouseExited
        lblMyRoute.setForeground(Color.black);
    }//GEN-LAST:event_lblMyRouteMouseExited

    private void lblMyOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyOrderMouseEntered
    }//GEN-LAST:event_lblMyOrderMouseEntered

    private void lblMyOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyOrderMouseExited
    }//GEN-LAST:event_lblMyOrderMouseExited

    private void lblMyOrderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyOrderMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblMyOrder.setCursor(c);
    }//GEN-LAST:event_lblMyOrderMouseMoved

    private void lblIWantGoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIWantGoMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblIWantGo.setCursor(c);
    }//GEN-LAST:event_lblIWantGoMouseMoved

    private void lblSendBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSendBoxMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblSendBox.setCursor(c);
    }//GEN-LAST:event_lblSendBoxMouseMoved

    private void lblCarryManOrBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCarryManOrBoxMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblCarryManOrBox.setCursor(c);
    }//GEN-LAST:event_lblCarryManOrBoxMouseMoved

    private void lblNotificationsMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotificationsMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblNotifications.setCursor(c);
    }//GEN-LAST:event_lblNotificationsMouseMoved

    private void lblLogOutMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblLogOut.setCursor(c);
    }//GEN-LAST:event_lblLogOutMouseMoved

    private void lblEquipmentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEquipmentMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblEquipment.setCursor(c);
    }//GEN-LAST:event_lblEquipmentMouseMoved

    private void lblMyRouteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMyRouteMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblMyRoute.setCursor(c);
    }//GEN-LAST:event_lblMyRouteMouseMoved

    private void btnUpdateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseMoved

    private void lblNameSurnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameSurnameMouseClicked
        UpdatePage update = new UpdatePage(u);
        update.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblNameSurnameMouseClicked

    private void lblNameSurnameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameSurnameMouseEntered
        lblNameSurname.setForeground(Color.white);
    }//GEN-LAST:event_lblNameSurnameMouseEntered

    private void lblNameSurnameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameSurnameMouseExited
        lblNameSurname.setForeground(Color.black);
    }//GEN-LAST:event_lblNameSurnameMouseExited

    private void lblNameSurnameMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameSurnameMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblNameSurname.setCursor(c);
    }//GEN-LAST:event_lblNameSurnameMouseMoved

    private void lblMessagesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessagesMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblMessages.setCursor(c);
    }//GEN-LAST:event_lblMessagesMouseMoved

    private void lblMessagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMessagesMouseClicked
        MessagesPage ms = new MessagesPage(u);
        ms.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblMessagesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblCarryManOrBox;
    private javax.swing.JLabel lblEquipment;
    private javax.swing.JLabel lblIWantGo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblMessages;
    private javax.swing.JLabel lblMessagesCount;
    private javax.swing.JLabel lblMyOrder;
    private javax.swing.JLabel lblMyOrderCount;
    private javax.swing.JLabel lblMyRoute;
    private javax.swing.JLabel lblNameSurname;
    private javax.swing.JLabel lblNotificationCount;
    private javax.swing.JLabel lblNotifications;
    private javax.swing.JLabel lblSendBox;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
