/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Notifications;
import Pojo.Users;
import java.awt.Color;

/**
 *
 * @author TT
 */
public class SendOrder extends javax.swing.JFrame {

    /**
     * Creates new form SendOrder
     */
    DBConnection dbc = new DBConnection();
    Users u = null;
    int id_to = 0;
    int id_route = 0;
    int PassengerCount = 0;
    double LuggageCount = 0;
    String keyword = "";

    public SendOrder() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public SendOrder(Users u, int id_to, int id_route, int PassengerCount, double LuggageCount, String keyword) {
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;
        this.id_to = id_to;
        this.id_route = id_route;

        this.PassengerCount = PassengerCount;
        this.LuggageCount = LuggageCount;
        this.keyword = keyword;

        lblError.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SpPassengerCount = new javax.swing.JSpinner();
        SpLuggageCount = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblSendOrderBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Adam Sayı");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 22, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Yük miqdarı");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Qeyd");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 96, -1, -1));

        SpPassengerCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(SpPassengerCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 20, 73, -1));

        SpLuggageCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(SpLuggageCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 58, 73, -1));

        txtNote.setColumns(20);
        txtNote.setRows(5);
        jScrollPane1.setViewportView(txtNote);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 117, 260, -1));

        btnOk.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOk.setText("Təsdiqlə");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        getContentPane().add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 288, -1, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Ləğv et");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 288, 79, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 241, 260, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 1, 30, 25));

        lblSendOrderBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSendOrderBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SendOrderBCK.png"))); // NOI18N
        lblSendOrderBCK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblSendOrderBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (keyword == "IWantGo") {
            IWantToGo iw = new IWantToGo(u);
            iw.setVisible(true);
            dispose();
        }
        if (keyword == "IWantSend") {
            IWantToSend iw = new IWantToSend(u);
            iw.setVisible(true);
            dispose();
        }


    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        Notifications n = new Notifications();
        n.setUser_id_from(u.getId());
        n.setUser_id_to(id_to);
        n.setRoute_id(id_route);
        n.setCount_passenger((int) SpPassengerCount.getValue());
        n.setCount_luggage(Double.parseDouble(SpLuggageCount.getValue().toString()));
        n.setNote(txtNote.getText());
  
        if (Integer.parseInt(SpPassengerCount.getValue().toString()) != 0 || Double.parseDouble(SpLuggageCount.getValue().toString()) != 0) {
            if (PassengerCount >= Integer.parseInt(SpPassengerCount.getValue().toString())
                    && LuggageCount >= Double.parseDouble(SpLuggageCount.getValue().toString())) {
                if ((dbc.countSenderNotificationPass(u.getId(), id_to, id_route) + Integer.parseInt(SpPassengerCount.getValue().toString()))
                        <= PassengerCount
                        && (dbc.countSenderNotificationLuggage(u.getId(), id_to, id_route) + Double.parseDouble(SpLuggageCount.getValue().toString()))
                        <= LuggageCount) {
                    dbc.insertNotifications(n);
                    IWantToGo iw = new IWantToGo(u);
                    iw.setVisible(true);
                    dispose();
                } else {
                    lblError.setVisible(true);
                    lblError.setText("Sernisin sayi veya yuk miqdari uygun deyil");
                }
            } else {
                lblError.setVisible(true);
                lblError.setText("Sernisin sayi veya yuk miqdari uygun deyil");
            }
        } else {
            lblError.setVisible(true);
            lblError.setText("Sernisin sayi veya yuk miqdarını düzgün daxil edin");
        }


    }//GEN-LAST:event_btnOkActionPerformed

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        if (keyword == "IWantGo") {
            IWantToGo iw = new IWantToGo(u);
            iw.setVisible(true);
            dispose();
        }
        if (keyword == "IWantSend") {
            IWantToSend iw = new IWantToSend(u);
            iw.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SpLuggageCount;
    private javax.swing.JSpinner SpPassengerCount;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblSendOrderBCK;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextArea txtNote;
    // End of variables declaration//GEN-END:variables
}
