/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Users;
import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author TT
 */
public class SendMessagesPage extends javax.swing.JFrame {

    /**
     * Creates new form SendMessagesPage
     */
    DBConnection dbc = new DBConnection();
    Users u = null;
    int id;
    int Rid;
    int Eid;
    int Passenger_Count;
    Double Luggage_Count;
    String keyword;

    public SendMessagesPage() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public SendMessagesPage(Users u, int id, int Rid, int Eid, int Passenger_Count, Double Luggage_Count, String keyword) {
        initComponents();
        setLocationRelativeTo(this);

        this.u = u;
        this.id = id;
        this.Rid = Rid;
        this.Eid = Eid;
        this.Passenger_Count = Passenger_Count;
        this.Luggage_Count = Luggage_Count;
        this.keyword = keyword;
        Users us = dbc.findByid(id);
        lblNameSurname.setText(us.getName() + " " + us.getSurname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        lblNameSurname = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNotification = new javax.swing.JLabel();
        lblSendMessagesBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        txtMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMessageKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtMessage);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 229, -1));

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Ləğv et");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 174, -1, -1));

        btnSend.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSend.setText("Göndər");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 174, -1, -1));

        lblNameSurname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNameSurname.setText("Name Surname");
        getContentPane().add(lblNameSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 10, 130, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 1, 29, 25));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Kimə:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 10, -1, -1));

        lblNotification.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNotification.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(lblNotification, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 32, 200, 15));

        lblSendMessagesBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSendMessagesBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SendMessagesPageBCK.png"))); // NOI18N
        lblSendMessagesBCK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblSendMessagesBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        ShowAllForEquip s = new ShowAllForEquip(u, id, Rid, Eid, Passenger_Count, Luggage_Count, "ToGo");
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ShowAllForEquip s = new ShowAllForEquip(u, id, Rid, Eid, Passenger_Count, Luggage_Count, "ToGo");
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if (!txtMessage.getText().isEmpty()) {
            dbc.insertMessage(u.getId(), id, txtMessage.getText());
            txtMessage.setText("");
            lblNotification.setText("Mesaj göndərildi");
            lblNotification.setForeground(Color.green);
        } else {
            ErrorDialog er = new ErrorDialog(this, true, "Mesaj daxil edilməmişdir");
            er.setVisible(true);
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void txtMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMessageKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txtMessage.getText().isEmpty()) {
                dbc.insertMessage(u.getId(), id, txtMessage.getText());
                txtMessage.setText("");
                lblNotification.setText("Mesaj göndərildi");
                lblNotification.setForeground(Color.green);
            } else {
                ErrorDialog er = new ErrorDialog(this, true, "Mesaj daxil edilməmişdir");
                er.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtMessageKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendMessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendMessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendMessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendMessagesPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendMessagesPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameSurname;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblSendMessagesBCK;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextArea txtMessage;
    // End of variables declaration//GEN-END:variables
}
