/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import java.awt.Cursor;

/**
 *
 * @author TT
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public StartPage() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblBlackBoy1 = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        lblStartPageBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblLoginMouseMoved(evt);
            }
        });
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 5, 90, 28));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reklam2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 130, 430));

        lblBlackBoy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBlackBoy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Reklam1.png"))); // NOI18N
        lblBlackBoy1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblBlackBoy1MouseMoved(evt);
            }
        });
        getContentPane().add(lblBlackBoy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, 430));

        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblXMouseMoved(evt);
            }
        });
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 4, 30, 30));

        lblStartPageBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStartPageBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StartPageBCK.png"))); // NOI18N
        getContentPane().add(lblStartPageBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_lblLoginMouseClicked

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void lblBlackBoy1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBlackBoy1MouseMoved


    }//GEN-LAST:event_lblBlackBoy1MouseMoved

    private void lblLoginMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblLogin.setCursor(c);
    }//GEN-LAST:event_lblLoginMouseMoved

    private void lblXMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseMoved
        Cursor c = new Cursor(Cursor.HAND_CURSOR);
        lblX.setCursor(c);
    }//GEN-LAST:event_lblXMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBlackBoy1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblStartPageBCK;
    private javax.swing.JLabel lblX;
    // End of variables declaration//GEN-END:variables
}
