/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Pojo.Users;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author TT
 */
public class UpdatePage extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePage
     */
    JFileChooser chooser = new JFileChooser();
    File f = null;
    byte b[];

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    DBConnection dbc = new DBConnection();
    Users u;

    public UpdatePage() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public UpdatePage(Users u) {
        initComponents();
        setLocationRelativeTo(this);
        this.u = u;
        b = u.getImage();

        lblError.setVisible(false);

        try {
            txtName.setText(u.getName());
            txtSurname.setText(u.getSurname());
            txtFatherName.setText(u.getFather_name());
            txtEmail.setText(u.getEmail());
            txtUsername.setText(u.getUsername());
            txtPhone.setText(u.getPhone());
            dtBirth.setDate(sdf.parse(u.getDate_of_birth()));
            if (u.getLanguages().contains("AZ")) {
                cbAZ.setSelected(true);
            }
            if (u.getLanguages().contains("TR")) {
                cbTR.setSelected(true);
            }
            if (u.getLanguages().contains("EN")) {
                cbEN.setSelected(true);
            }
            if (u.getLanguages().contains("RU")) {
                cbRU.setSelected(true);
            }

            if (u.getGender() == 'M') {
                rbMale.setSelected(true);
            } else {
                rbFemale.setSelected(true);
            }

            txtAreaDescription.setText(u.getDescription());

            if (u.getImage() != null) {
                Image img = Toolkit.getDefaultToolkit().createImage(u.getImage()).getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_DEFAULT);
                ImageIcon imageIcon = new ImageIcon(img);
                lblImage.setIcon(imageIcon);

            } else {
                lblImage.setIcon(lblImage.getIcon());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtFatherName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        dtBirth = new com.toedter.calendar.JDateChooser();
        cbTR = new javax.swing.JCheckBox();
        cbEN = new javax.swing.JCheckBox();
        cbRU = new javax.swing.JCheckBox();
        cbAZ = new javax.swing.JCheckBox();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaDescription = new javax.swing.JTextArea();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnChoosePhoto = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnFreezeAccount = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblUpdateBck = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ad");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        getContentPane().add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 29, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Soyad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Ata adı");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("E-poçta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("İstifadəçi adı");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Telefon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Doğum tarixi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 259, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Dil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cins");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 338, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Haqqında");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 379, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 31, 160, -1));
        getContentPane().add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 69, 160, -1));
        getContentPane().add(txtFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 107, 160, -1));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 145, 160, -1));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 183, 160, -1));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 221, 160, -1));
        getContentPane().add(dtBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 259, 160, -1));

        cbTR.setBackground(new java.awt.Color(89, 178, 178));
        cbTR.setForeground(new java.awt.Color(255, 255, 255));
        cbTR.setText("TR");
        cbTR.setOpaque(false);
        getContentPane().add(cbTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        cbEN.setBackground(new java.awt.Color(89, 178, 178));
        cbEN.setForeground(new java.awt.Color(255, 255, 255));
        cbEN.setText("EN");
        cbEN.setOpaque(false);
        getContentPane().add(cbEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        cbRU.setBackground(new java.awt.Color(89, 178, 178));
        cbRU.setForeground(new java.awt.Color(255, 255, 255));
        cbRU.setText("RU");
        cbRU.setOpaque(false);
        getContentPane().add(cbRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        cbAZ.setBackground(new java.awt.Color(89, 178, 178));
        cbAZ.setForeground(new java.awt.Color(255, 255, 255));
        cbAZ.setText("AZ");
        cbAZ.setOpaque(false);
        getContentPane().add(cbAZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        rbMale.setBackground(new java.awt.Color(89, 178, 178));
        rbMale.setForeground(new java.awt.Color(255, 255, 255));
        rbMale.setText("Kisi");
        rbMale.setOpaque(false);
        getContentPane().add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        rbFemale.setBackground(new java.awt.Color(89, 178, 178));
        rbFemale.setForeground(new java.awt.Color(255, 255, 255));
        rbFemale.setText("Qadin");
        rbFemale.setOpaque(false);
        getContentPane().add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        txtAreaDescription.setColumns(20);
        txtAreaDescription.setRows(5);
        jScrollPane1.setViewportView(txtAreaDescription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 256, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdate.setText("Yadda saxla");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, -1, -1));
        btnUpdate.getAccessibleContext().setAccessibleDescription("");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Ləğv et");
        btnCancel.setPreferredSize(new java.awt.Dimension(91, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 470, -1, -1));

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RegisterProfilePicture.png"))); // NOI18N
        lblImage.setOpaque(true);
        getContentPane().add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 37, 140, 140));

        btnChoosePhoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnChoosePhoto.setText("Şəkil seç");
        btnChoosePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoosePhotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnChoosePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 190, 90, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("Error Label");
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 230, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Şifrəni dəyiş");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, -1));

        btnFreezeAccount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnFreezeAccount.setText("Hesabı dondur");
        btnFreezeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreezeAccountActionPerformed(evt);
            }
        });
        getContentPane().add(btnFreezeAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 140, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Şəkili sil");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 90, -1));

        lblUpdateBck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UpdateBCK.png"))); // NOI18N
        lblUpdateBck.setText("jLabel11");
        lblUpdateBck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblUpdateBck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        if (u.getRole() != 0) {
            MyProfile mp = new MyProfile(u);
            mp.setVisible(true);
            dispose();
        } else {
            AdminPage a = new AdminPage(u);
            a.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (dbc.findByUsernameId(txtUsername.getText()) == u.getId() || dbc.findByUsername(txtUsername.getText()) == 0) {
            String lang = "";
            u.setName(txtName.getText());
            u.setSurname(txtSurname.getText());
            u.setFather_name(txtFatherName.getText());
            u.setEmail(txtEmail.getText());
            u.setUsername(txtUsername.getText());
            u.setPhone(txtPhone.getText());
            u.setDate_of_birth(sdf.format(dtBirth.getDate()));
            if (cbAZ.isSelected()) {
                lang = lang + cbAZ.getText() + ",";
            }
            if (cbEN.isSelected()) {
                lang = lang + cbEN.getText() + ",";
            }
            if (cbRU.isSelected()) {
                lang = lang + cbRU.getText() + ",";
            }
            if (cbTR.isSelected()) {
                lang = lang + cbTR.getText() + ",";
            }
            u.setLanguages(lang);

            if (rbFemale.isSelected()) {
                u.setGender('F');
            } else if (rbMale.isSelected()) {
                u.setGender('M');
            }
            u.setDescription(txtAreaDescription.getText());
            u.setImage(b);
            dbc.updateUsers(u);

            MyProfile mp = new MyProfile(u);
            mp.setVisible(true);
            dispose();
        } else {
            lblError.setVisible(true);
            lblError.setForeground(Color.red);
            lblError.setBackground(Color.white);
            lblError.setText(txtUsername.getText() + " istifadəçi adı mövcuddur");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (u.getRole() != 0) {
            MyProfile mp = new MyProfile(u);
            mp.setVisible(true);
            dispose();
        } else {
            AdminPage a = new AdminPage(u);
            a.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnChoosePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoosePhotoActionPerformed
        chooser.showOpenDialog(null);
        f = chooser.getSelectedFile();

        if (f != null) {
            b = new byte[(int) f.length()];
            try {
                InputStream oxu = new FileInputStream(f);
                oxu.read(b);
            } catch (Exception e) {
                e.printStackTrace();
            }
            Toolkit toolkitLogo = Toolkit.getDefaultToolkit();
            Image imageLogo = toolkitLogo.getImage(f.getAbsolutePath());
            lblImage.setIcon(new ImageIcon(imageLogo.getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), java.awt.Image.SCALE_DEFAULT)));

        } else {
            b = u.getImage();
        }
    }//GEN-LAST:event_btnChoosePhotoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ChangePassword changepassword = new ChangePassword(u);
        changepassword.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnFreezeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFreezeAccountActionPerformed
        FreezeAccountDialog freeze = new FreezeAccountDialog(this, true, u, "Freeze");
        freeze.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFreezeAccountActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FreezeAccountDialog freeze = new FreezeAccountDialog(this, true, u, "DeleteImage");
        freeze.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChoosePhoto;
    private javax.swing.JButton btnFreezeAccount;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbAZ;
    private javax.swing.JCheckBox cbEN;
    private javax.swing.JCheckBox cbRU;
    private javax.swing.JCheckBox cbTR;
    private com.toedter.calendar.JDateChooser dtBirth;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblUpdateBck;
    private javax.swing.JLabel lblX;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextArea txtAreaDescription;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
