/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnected.DBConnection;
import Models.UsersTableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author TT
 */
public class UsersList extends javax.swing.JFrame {

    /**
     * Creates new form UsersList
     */
    DBConnection dbc = new DBConnection();

    public UsersList() {
        initComponents();
        setLocationRelativeTo(this);
        refresh();
    }

    public void refresh() {
        List<String> header = new ArrayList<String>();
        header.add("ID");
        header.add("Ad");
        header.add("Soyad");
        header.add("Email");
        header.add("Telefon");
        header.add("Cins");
        header.add("Dil");
        header.add("Status");

        UsersTableModel model = new UsersTableModel(dbc.listUsers(), header);
        tblUsers.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnShowAll = new javax.swing.JButton();
        btnBlock = new javax.swing.JButton();
        btnUnBlock = new javax.swing.JButton();
        lblUserListBCK = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(89, 178, 178));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setBackground(new java.awt.Color(255, 255, 255));
        lblX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblX.setForeground(new java.awt.Color(204, 0, 0));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("X");
        lblX.setOpaque(true);
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblXMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblXMouseExited(evt);
            }
        });
        jPanel1.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 2, 25, 25));

        jScrollPane1.setViewportView(tblUsers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 33, 795, 306));

        btnShowAll.setText("ShowAll");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnShowAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 345, -1, -1));

        btnBlock.setText("Block");
        btnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBlockActionPerformed(evt);
            }
        });
        jPanel1.add(btnBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 345, -1, -1));

        btnUnBlock.setText("UnBlock");
        btnUnBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnBlockActionPerformed(evt);
            }
        });
        jPanel1.add(btnUnBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 345, -1, -1));

        lblUserListBCK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserListBCK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/UserListBCK.png"))); // NOI18N
        jPanel1.add(lblUserListBCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 796, 380));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void lblXMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseEntered
        lblX.setBackground(Color.red);
        lblX.setForeground(Color.white);
    }//GEN-LAST:event_lblXMouseEntered

    private void lblXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseExited
        lblX.setBackground(Color.white);
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_lblXMouseExited

    private void btnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBlockActionPerformed
        try {
            BlockDeleteDialog block = new BlockDeleteDialog(this, true, Integer.parseInt(tblUsers.getValueAt(tblUsers.getSelectedRow(), 0).toString()), "Block");
            block.setVisible(true);
            refresh();
        } catch (Exception e) {
            ErrorDialog er = new ErrorDialog(this, true, "Her hansi bir obyekt secilmeyib!");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnBlockActionPerformed

    private void btnUnBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnBlockActionPerformed
        try {
            BlockDeleteDialog block = new BlockDeleteDialog(this, true, Integer.parseInt(tblUsers.getValueAt(tblUsers.getSelectedRow(), 0).toString()), "UnBlock");
            block.setVisible(true);
            refresh();
        } catch (Exception e) {
            ErrorDialog er = new ErrorDialog(this, true, "Her hansi bir obyekt secilmeyib!");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnUnBlockActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        try {
            ShowAllDialog show = new ShowAllDialog(this, true, Integer.parseInt(tblUsers.getValueAt(tblUsers.getSelectedRow(), 0).toString()));
            show.setVisible(true);
        } catch (Exception e) {
            ErrorDialog er = new ErrorDialog(this, true, "Her hansi bir obyekt secilmeyib!");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnShowAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlock;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton btnUnBlock;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUserListBCK;
    private javax.swing.JLabel lblX;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
